<?php
namespace Heystack\Core\Generate;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 20:41:24.
 */
class YamlDataObjectSchemaTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var YamlDataObjectSchema
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new YamlDataObjectSchema;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testSchema()
    {
        $this->markTestIncomplete();
    }
}
