{$PHPTag.RAW}
/**
 * $Name
 *
 * This class has been auto-generated by Heystack
 */
class $Name extends $Extends
{
<% if $managed_models %>    private static \$managed_models = $managed_models.RAW;<% end_if %>
<% if $url_segment %>    private static  \$url_segment = $url_segment.RAW;<% end_if %>
<% if $menu_title %>    private static  \$menu_title = $menu_title.RAW;<% end_if %>
}