<?php
namespace Heystack\Core\Console\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 20:40:49.
 */
class GenerateContainerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GenerateContainer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new GenerateContainer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    public function testRun()
    {
        $this->markTestIncomplete();
    }
}
