$P
/**
 * $DataObjectName
 *
 * This class has been auto-generated by Heystack
 */
class $Name extends $Extends
{

<% if db %>public static {$D}db = $db;<% end_if %>
<% if has_one %>public static {$D}has_one = $has_one;<% end_if %>
<% if has_many %>public static {$D}has_many = $has_many;<% end_if %>
    
}