$P
/**
 * $DataObjectName
 *
 * This class has been auto-generated by Heystack
 */
class $DataObjectName extends $ExtendedDataObject
{
    
<% if summary_fields %>public static {$D}summary_fields = $summary_fields;<% end_if %>

}