<?php
namespace Heystack\Core\State\Backends;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 20:41:59.
 */
class MemcacheTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Memcache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Memcache;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heystack\Core\State\Backends\Memcache::getKeys
     * @todo   Implement testGetKeys().
     */
    public function testGetKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Core\State\Backends\Memcache::addKey
     * @todo   Implement testAddKey().
     */
    public function testAddKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Core\State\Backends\Memcache::setByKey
     * @todo   Implement testSetByKey().
     */
    public function testSetByKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Core\State\Backends\Memcache::getByKey
     * @todo   Implement testGetByKey().
     */
    public function testGetByKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Core\State\Backends\Memcache::removeByKey
     * @todo   Implement testRemoveByKey().
     */
    public function testRemoveByKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Core\State\Backends\Memcache::removeAll
     * @todo   Implement testRemoveAll().
     */
    public function testRemoveAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
