<?php
namespace Heystack\Core\Storage\Backends\SilverStripeOrm;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 20:42:18.
 */
class BackendTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Backend
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Backend;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heystack\Core\Storage\Backends\SilverStripeOrm\Backend::addDataProvider
     * @todo   Implement testAddDataProvider().
     */
    public function testAddDataProvider()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Core\Storage\Backends\SilverStripeOrm\Backend::hasDataProvider
     * @todo   Implement testHasDataProvider().
     */
    public function testHasDataProvider()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Core\Storage\Backends\SilverStripeOrm\Backend::getIdentifier
     * @todo   Implement testGetIdentifier().
     */
    public function testGetIdentifier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Core\Storage\Backends\SilverStripeOrm\Backend::write
     * @todo   Implement testWrite().
     */
    public function testWrite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
