<?php
namespace Heystack\Subsystem\Core\State\Backends;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 20:42:01.
 */
class SessionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Session
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Session;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heystack\Subsystem\Core\State\Backends\Session::getKeys
     * @todo   Implement testGetKeys().
     */
    public function testGetKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Core\State\Backends\Session::setByKey
     * @todo   Implement testSetByKey().
     */
    public function testSetByKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Core\State\Backends\Session::getByKey
     * @todo   Implement testGetByKey().
     */
    public function testGetByKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Core\State\Backends\Session::removeByKey
     * @todo   Implement testRemoveByKey().
     */
    public function testRemoveByKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Core\State\Backends\Session::removeAll
     * @todo   Implement testRemoveAll().
     */
    public function testRemoveAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
