#!/bin/bash

PATHS=( )

for dir in `ls .`
do
    if [ -d $dir ] && [ -f "$dir/_heystack_subsystem" ]; then

        for sub in `ls $dir/code/`
        do
            if [ -d "$dir/code/$sub" ]; then
                PATHS+=("$dir/code/$sub")
            fi
        done

        for vendor in `ls $dir/vendor/`
        do
            if [ -d "$dir/vendor/$vendor" ]; then
                PATHS+=("$dir/vendor/$vendor")
            fi
        done

    fi
done

IFS=","

phpdoc run --title Heystack -p -d "${PATHS[*]}" -t ../doc --template "heystack/tools/theme//heystack"