#!/bin/bash

PATHS=( )

for dir in `ls .`
do
    if [ -d $dir ] && [ -f "$dir/_heystack_subsystem" ]; then

        for sub in `ls $dir/code/`
        do
            PATHS+=("$dir/code/$sub")
        done

    fi
done

IFS=","

phpdoc run --title Heystack -p -d "${PATHS[*]}" -t ../doc