<?php
namespace Heystack\Subsystem\Core\Test;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-22 at 09:44:55.
 */
class ContainerExtensionConfigProcessorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ContainerExtensionConfigProcessor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testProcessor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
