<?php
namespace Heystack\Subsystem\Core\Test;

use Heystack\Subsystem\Core\ContainerExtension;
use Heystack\Subsystem\Core\ContainerExtensionConfigProcessor;

use Heystack\Subsystem\Core\Exception\ConfigurationException;

use Symfony\Component\DependencyInjection\ContainerBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-22 at 09:44:55.
 */
class ContainerExtensionConfigProcessorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ContainerExtensionConfigProcessor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $this->object = new ContainerExtension();
        $this->object->setFolder('/tests/Heystack/Subsystem/Core/Test/services/');

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testProcessConfig()
    {

        $builder = new ContainerBuilder();

        $this->object->load(
            array(
                array(
                    'parameters' => array(
                        'test' => 'test2'
                    )
                )
            ),
            $builder
        );

        $this->assertEquals('test2', $builder->getParameter('test'));

        $message = null;

        try {

            $this->object->load(
                array(
                    array(
                        'parameters' => array(
                            'test' => '$$$'
                        )
                    )
                ),
                $builder
            );

        } catch (ConfigurationException $e) {

            $message = $e->getMessage();

        }

        $this->assertNotNull($message);

    }
}