<?php

namespace Heystack\Subsystem\Core\Test;

use Heystack\Subsystem\Core\Events;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-22 at 14:59:54.
 */
class EventsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testConsts()
    {

        $this->assertEquals('heystack.ready', Events::READY);

    }
}
