<?php

namespace Heystack\Subsystem\Core\Test;

use Heystack\Subsystem\Core\MergeExtensionArgumentsConfigurationPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-22 at 09:42:26.
 */
class MergeExtensionArgumentsConfigurationPassTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Heystack\Subsystem\Core\MergeExtensionArgumentsConfigurationPass
     */
    protected $object;

    /**
     * @var Symfony\Component\DependencyInjection\ContainerBuilder
     */
    protected $containerBuilder;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $this->object = new MergeExtensionArgumentsConfigurationPass();
        $this->containerBuilder = new ContainerBuilder;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

        $this->object = null;

    }

    /**
     * @covers Heystack\Subsystem\Core\MergeExtensionArgumentsConfigurationPass::process
     */
    public function testProcess()
    {

        $containerBuilder = new ContainerBuilder();

        $containerBuilder->register('test', 'Test')->addArgument('test1');

        $containerBuilder->registerExtension(new TestContainerExtension(array('test2')));

        $this->object->process($containerBuilder);

        $this->assertEquals(array('test1'), $containerBuilder->getDefinition('test')->getArguments());

        $containerBuilder->loadFromExtension('test_extension');

        $this->object->process($containerBuilder);

        $this->assertEquals(array('test2'), $containerBuilder->getDefinition('test')->getArguments());

    }
}
