<?php
namespace Heystack\Subsystem\Core\Test;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-22 at 09:42:51.
 */
class MergeExtensionCallsConfigurationPassTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MergeExtensionCallsConfigurationPass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heystack\Subsystem\Core\MergeExtensionCallsConfigurationPass::process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
