<?php
namespace Heystack\Subsystem\Core\Test;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-22 at 09:44:11.
 */
class MysiteContainerExtensionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MysiteContainerExtension
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heystack\Subsystem\Core\MysiteContainerExtension::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Core\MysiteContainerExtension::getNamespace
     * @todo   Implement testGetNamespace().
     */
    public function testGetNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Core\MysiteContainerExtension::getXsdValidationBasePath
     * @todo   Implement testGetXsdValidationBasePath().
     */
    public function testGetXsdValidationBasePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Core\MysiteContainerExtension::getAlias
     * @todo   Implement testGetAlias().
     */
    public function testGetAlias()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
