<?php

namespace Heystack\Subsystem\Core\Test;

use Heystack\Subsystem\Core\Services;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-22 at 16:32:20.
 */
class ServicesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testConstruct()
    {

        $this->assertInternalType('object', new Services);

    }

    public function testConsts()
    {

        $this->assertEquals('memcache', Services::MEMCACHE);
        $this->assertEquals('session', Services::SESSION);
        $this->assertEquals('backend_memcache', Services::BACKEND_MEMCACHE);
        $this->assertEquals('backend_global_memcache', Services::BACKEND_GLOBAL_MEMCACHE);
        $this->assertEquals('backend_session', Services::BACKEND_SESSION);
        $this->assertEquals('state', Services::STATE);
        $this->assertEquals('state_global', Services::STATE_GLOBAL);
        $this->assertEquals('config', Services::CONFIG);
        $this->assertEquals('event_dispatcher', Services::EVENT_DISPATCHER);
        $this->assertEquals('input_processor_handler', Services::INPUT_PROCESSOR_HANDLER);
        $this->assertEquals('output_processor_handler', Services::OUTPUT_PROCESSOR_HANDLER);
        $this->assertEquals('monolog_multiline_formatter', Services::MONOLOG_MULTILINE_FORMATTER);
        $this->assertEquals('monolog_web_processor', Services::MONOLOG_WEB_PROCESSOR);
        $this->assertEquals('monolog_peak_memory_processor', Services::MONOLOG_PEAK_MEMORY_PROCESSOR);
        $this->assertEquals('monolog_introspection_processor', Services::MONOLOG_INTROSPECTION_PROCESSOR);
        $this->assertEquals('monolog_stream_handler', Services::MONOLOG_STREAM_HANDLER);
        $this->assertEquals('monolog_mail_handler', Services::MONOLOG_MAIL_HANDLER);
        $this->assertEquals('monolog_chrome_handler', Services::MONOLOG_CHROME_HANDLER);
        $this->assertEquals('monolog', Services::MONOLOG);
        $this->assertEquals('monolog_dev', Services::MONOLOG_DEV);
        $this->assertEquals('dataobject_generator', Services::DATAOBJECT_GENERATOR);
        $this->assertEquals('dataobject_generator_input_processor', Services::DATAOBJECT_GENERATOR_INPUT_PROCESSOR);
        $this->assertEquals('cli_input_processor_handler', Services::CLI_INPUT_PROCESSOR_HANDLER);
        $this->assertEquals('ss_orm_backend', Services::SS_ORM_BACKEND);
        $this->assertEquals('storage', Services::STORAGE);

    }
}
